verbType2verb = {
    "{takeVerb}": ["take", "get", "grasp", "fetch"],
    "{placeVerb}": ["put", "place"],
    "{deliverVerb}": ["bring", "give", "deliver"],
    "{bringVerb}": ["bring", "give"],
    "{goVerb}": ["go", "navigate"],
    "{findVerb}": ["find", "locate", "look for"],
    "{talkVerb}": ["tell", "say"],
    "{answerVerb}": ["answer"],
    "{meetVerb}": ["meet"],
    "{tellVerb}": ["tell"],
    "{greetVerb}": ["greet", "salute", "say hello to", "introduce yourself to"],
    "{countVerb}": ["tell me how many"],
    "{followVerb}": ["follow"],
    "{guideVerb}": ["guide", "escort", "take", "lead"],
    # "{rememberVerb}": ["meet", "contact", "get to know", "get acquainted with"],
    # "{describeVerb}": ["tell me how", "describe"],
    # "{offerVerb}": ["offer"],
    # "{accompanyVerb}": ["accompany"]
}

verbType2cmdName = {
    "{takeVerb}": ["takeObjFromPlcmt"],
    "{placeVerb}": [],
    "{deliverVerb}": [],
    "{bringVerb}": ["bringMeObjFromPlcmt"],
    "{goVerb}": ["goToLoc"],
    "{findVerb}": ["findPrsInRoom", "findObjInRoom"],
    "{talkVerb}": ["talkInfoToGestPrsInRoom"],
    "{answerVerb}": ["answerToGestPrsInRoom"],
    "{meetVerb}": ["meetPrsAtBeac", "meetNameAtLocThenFindInRm"],
    "{tellVerb}": ["tellPrsInfoInLoc", "tellCatPropOnPlcmt"],
    "{greetVerb}": ["greetClothDscInRm", "greetNameInRm"],
    "{countVerb}": ["countObjOnPlcmt", "countPrsInRoom", "countClothPrsInRoom"],
    "{followVerb}": ["followNameFromBeacToRoom", "followPrsAtLoc"],
    "{guideVerb}": ["guideNameFromBeacToBeac", "guidePrsFromBeacToBeac", "guideClothPrsFromBeacToBeac"],
    # "remember": [],
    # "describe": [],
    # "offer": [],
    # "accompany": []
}

cmdName2cmdStr = {
    "goToLoc": "{goVerb} {toLocPrep} the {loc_room} then {followup}",
    "takeObjFromPlcmt": "{takeVerb} {art} {obj_singCat} {fromLocPrep} the {plcmtLoc} and {followup}",
    "findPrsInRoom": "{findVerb} a {gestPers_posePers} {inLocPrep} the {room} and {followup}",
    "findObjInRoom": "{findVerb} {art} {obj_singCat} {inLocPrep} the {room} then {takeVerb} it and {followup}",
    "meetPrsAtBeac": "{meetVerb} {name} {inLocPrep} the {room} and {followup}",
    "countObjOnPlcmt": "{countVerb} {plurCat} there are {onLocPrep} the {plcmtLoc}",
    "countPrsInRoom": "{countVerb} {gestPersPlur_posePersPlur} are {inLocPrep} the {room}",
    "tellPrsInfoInLoc": "{tellVerb} me the {persInfo} of the person {inRoom_atLoc}",
    "talkInfoToGestPrsInRoom": "{talkVerb} {talk} {talkPrep} the {gestPers} {inLocPrep} the {room}",
    "answerToGestPrsInRoom": "{answerVerb} the {question} {ofPrsPrep} the {gestPers} {inLocPrep} the {room}",
    "followNameFromBeacToRoom": "{followVerb} {name} {fromLocPrep} the {loc} {toLocPrep} the {room}",
    "guideNameFromBeacToBeac": "{guideVerb} {name} {fromLocPrep} the {loc} {toLocPrep} the {loc_room}",
    "guidePrsFromBeacToBeac": "{guideVerb} the {gestPers_posePers} {fromLocPrep} the {loc} {toLocPrep} the {loc_room}",
    "guideClothPrsFromBeacToBeac": "{guideVerb} the person wearing a {colorClothe} {fromLocPrep} the {loc} {toLocPrep} the {loc_room}",
    "bringMeObjFromPlcmt": "{bringVerb} me {art} {obj} {fromLocPrep} the {plcmtLoc}",
    "tellCatPropOnPlcmt": "{tellVerb} me what is the {objComp} {singCat} {onLocPrep} the {plcmtLoc}",
    "greetClothDscInRm": "{greetVerb} the person wearing {art} {colorClothe} {inLocPrep} the {room} and {followup}",
    "greetNameInRm": "{greetVerb} {name} {inLocPrep} the {room} and {followup}",
    "meetNameAtLocThenFindInRm": "{meetVerb} {name} {atLocPrep} the {loc} then {findVerb} them {inLocPrep} the {room}",
    "countClothPrsInRoom": "{countVerb} people {inLocPrep} the {room} are wearing {colorClothes}",
    "tellPrsInfoAtLocToPrsAtLoc": "{tellVerb} the {persInfo} of the person {atLocPrep} the {loc} to the person {atLocPrep} the {loc2}",
    "followPrsAtLoc": "{followVerb} the {gestPers_posePers} {inRoom_atLoc}"
}

followupName2followupStr = {
    "findTakeObj": "{findVerb} {art} {obj_singCat} and {takeVerb} it and  {followup}",
    "findPrs": "{findVerb} the {gestPers_posePers} and {followup}",
    "meetName": "{meetVerb} {name} and {followup}",
    "placeObjOnPlcmt": "{placeVerb} it {onLocPrep} the {plcmtLoc}",
    "deliverObjToMe": "{deliverVerb} it to me",
    "deliverObjToPrsInRoom": "{deliverVerb} it {deliverPrep} the {gestPers_posePers} {inLocPrep} the {room}",
    "deliverObjToNameAtBeac": "{deliverVerb} it {deliverPrep} {name} {inLocPrep} the {room}",
    "talkInfo": "{talkVerb} {talk}",
    "answerQuestion": "{answerVerb} a {question}",
    "followPrs": "{followVerb} them",
    "followPrsToRoom": "{followVerb} them {toLocPrep} the {loc_room}",
    "guidePrsToBeacon": "{guideVerb} them {toLocPrep} the {loc_room}",
}