name_to_itemtype = {
    'dubbelfris': 1,
    'water': 1,
    'fanta': 1,
    'cola': 1,
    'milk': 1,
    'ice tea': 1,
    'big coke': 1,
    'banana': 3,
    'apple': 3,
    'strawberry': 3,
    'pear': 3,
    'peach': 3,
    'lemon': 3,
    'orange': 3,
    'plum': 3,
    'pringles': 5,
    'crisps': 5,
    'candy': 5,
    'yellow bag': 7,
    'liquorice': 5,
    'stroopwaffles': 5,
    'tictac': 5,
    'pea soup': 2,
    'cornflakes': 2,
    'mayonnaise': 2,
    'curry': 2,
    'hagelslag': 2,
    'white bag': 7,
    'pancake mix': 2,
    'sausages': 2,
    'plate': 6,
    'fork': 6,
    'bowl': 6,
    'spoon': 6,
    'cup': 6,
    'knife': 6,
    'soap': 0,
    'candle': 4,
}

# [side: 0, top: 1, bowl: 2, plate: 3, shelf: 4, bag:5]
name_to_grasping_type = {
    'dubbelfris': 0,
    'water': 0,
    'fanta': 0,
    'cola': 0,
    'milk': 0,
    'ice tea': 0,
    'big coke': 0,
    'banana': 0,
    'apple': 0,
    'strawberry': 0,
    'pear': 0,
    'peach': 0,
    'lemon': 0,
    'orange': 0,
    'plum': 0,
    'pringles': 0,
    'crisps': 0,
    'candy': 0,
    'yellow bag': 5,
    'liquorice': 0,
    'stroopwaffles': 0,
    'tictac': 0,
    'pea soup': 0,
    'cornflakes': 0,
    'mayonnaise': 0,
    'curry': 0,
    'hagelslag': 0,
    'white bag': 5,
    'pancake mix': 0,
    'sausages': 0,
    'plate': 3,
    'fork': 1,
    'bowl': 2,
    'spoon': 1,
    'cup': 0,
    'knife': 1,
    'soap': 0,
    'candle': 0,
}
